name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-server.yml'
      - 'server/Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/sticker-app
            git pull origin main
            docker build -t sticker-app ./server
            docker stop sticker-app || true
            docker rm sticker-app || true
            docker run -d \
              --name sticker-app \
              --network app-network \
              -p 5000:5000 \
              -e NODE_ENV=production \
              -e PORT=5000 \
              -e MONGODB_URI=mongodb://admin:password123@mongodb:27017/sticker-collection?authSource=admin \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              sticker-app 